### PR TITLE
multiple-choice

### PR DESCRIPTION
**Pull request by Steve2955**
`Draft for visibility`; tested on desktop and android; ~~only persistent checkboxes for now.~~

Example Format:

```md
# Test 1

<!-- md2apkg type multiple-choice -->

- [ ] A
- [ ] B
- [ ] C
- [ ] D

<!-- md2apkg split -->

- [ ] A
- [X] B
- [ ] C
- [X] D
```

Preview:

image

### CODE REVIEW

**Review by RvNovae — CHANGES_REQUESTED** [review]
Just tested it.

When I put:

```md
## Cities of Germany

<!-- md2apkg type multiple-choice -->

Which of the following cities are located within Thuringia?

- [X] Erfurt
- [ ] Frankfurt
- [ ] Munich
- [ ] Dresden
- [X] Gera
```

into a `md` file. I always get the following (no matter what I select):

image

However, when I use a markdown like:

```
## Cities of Germany

<!-- md2apkg type multiple-choice -->

Which of the following cities are located within Thuringia?

- [X] Erfurt
- [ ] Frankfurt
- [ ] Munich
- [ ] Dresden
- [X] Gera

## Cities of Germany 2

<!-- md2apkg type multiple-choice -->

Which of the following cities are located within Thuringia?

- [ ] Erfurt
- [ ] Frankfurt
- [ ] Munich
- [ ] Dresden
- [ ] Gera

<!-- md2apkg split -->

- [X] Erfurt
- [ ] Frankfurt
- [ ] Munich
- [ ] Dresden
- [X] Gera
```

(please note the mixing of short and long version) **both** work just fine.

When I try something like:

```md
## Cities of Germany

<!-- md2apkg type multiple-choice -->

Which of the following cities are located within Thuringia?

- [X] Erfurt
- [ ] Frankfurt
- [ ] Munich
- [ ] Dresden
- [X] Gera

## Cities of Germany 2

<!-- md2apkg type multiple-choice -->

Which of the following cities are located within Thuringia?

- [X] Erfurt
- [ ] Frankfurt
- [ ] Munich
- [ ] Dresden
- [X] Gera
```

(note the two short forms) only the **first** question works as expected but the second outputs NAN-%

Seems like something funky is going on with the short forms. Putting in a single long-version question works just fine.

If I have some more time I can take a look at the code later but I hope this helps.

**Comment by Steve2955** [comment]
@RvNovae Thank you for your testing. My quick investigation showed that, if the markdown file ends with a list, the closing list-tag (`</ul>`) is missing in the generated HTML which messes things up.

**Review by RvNovae — APPROVED** [review]
The NAN-Problem appears to be fixed now! :)

I only read the code somewhat thoroughly but I'd say it looks good to me. (I'm not that good of a Node/JS developer anyway 😅)
Thank you very much, this feature is excellent :D

**Comment by Steve2955** [comment]
@RvNovae Thank you very much for your feedback!

**Pull request merged**
